# Generated by Django 5.2.2 on 2025-06-06 22:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the note.', primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a short, descriptive title for the note.', max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Enter the detailed content of the note.', verbose_name='Description')),
                ('is_favourite', models.BooleanField(default=False, help_text='Mark this note as a favourite.', verbose_name='Is Favourite')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the note was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the note was last modified.', verbose_name='Last Updated')),
                ('owner', models.ForeignKey(help_text='The user who owns this note.', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['-updated_at'],
            },
        ),
    ]
